version: '3.8'

services:
  # 1. The Source of Truth
  postgres:
    image: postgres:16-alpine
    container_name: backend_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: assets_db
    ports:
      - "5433:5432"
    volumes:
      - ../migrations/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  # 2. The Cache & Job Status Tracker
  # redis:
  #   image: redis:7-alpine
  #   container_name: backend_redis
  #   ports:
  #     - "6379:6379"

  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    # network_mode: "host"
    volumes:
      - dragonflydata:/data

  # 3. The Message Queue
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: backend_rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ broker port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: strongpassword
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit tcp_listeners [{\"0.0.0.0\",5672}]"

  # 4. Metrics Scraper
  prometheus:
    image: prom/prometheus:latest
    container_name: backend_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # 5. Visualization Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: backend_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  postgres_data:
  dragonflydata: